version: '3.1'

services:

  mysql_db:
    image: mysql
    container_name: MysqlDev
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
      # MYSQL_ROOT_PASSWORD: ${DOCKER_mysql_db}
      MYSQL_ROOT_PASSWORD: "mysql"
    # volumes:
    #   - ~/Projetos/databases/volumes/mysql:/var/lib/mysql

  postgres_db:
    image: postgres
    container_name: PostgresDev
    environment:
      # POSTGRES_PASSWORD: ${DOCKER_postgres_db}
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - 5432:5432
    # restart: always
    # volumes:
    #   - ~/Projetos/databases/volumes/postgresql:/var/lib/postgresql/data 

  adminer:
    image: adminer
    container_name: AdminerDev
    restart: always
    ports:
      - 8888:8080

